Hovedopgave/Models/Station.cs
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

namespace Hovedopgave.Models
{
    public class Station
    {
        public int Id { get; set; }
        [DisplayName("Station navn")]
        public string Name { get; set; }
        [DisplayName("X Lokation")]
        public double LocationX { get; set; }
        [DisplayName("Y Lokation")]
        public double LocationY { get; set; }
        [DisplayName("Noter")]
        public string Notes { get; set; }

        public ICollection<Ticket>? Tickets { get; set; }
    }
}

Hovedopgave/Controllers/StationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Hovedopgave.Data;
using Hovedopgave.Models;
using Microsoft.AspNetCore.Authorization;
using log4net;

namespace Hovedopgave.Controllers
{
    [Authorize]
    public class StationsController : Controller
    {
        private readonly HovedopgaveContext _context;

        // create a static logger field
        private static ILog logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public StationsController(HovedopgaveContext context)
        {
            _context = context;
        }

        // GET: Stations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Station.ToListAsync());
        }

        // GET: Stations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var station = await _context.Station
                .FirstOrDefaultAsync(m => m.Id == id);
            if (station == null)
            {
                return NotFound();
            }

            return View(station);
        }

        // GET: Stations/Create
        public IActionResult Create()
        {
            logger.Info("Logger Test");
            return View();
        }

        // POST: Stations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,LocationX,LocationY,Notes")] Station station)
        {
            if (ModelState.IsValid)
            {
                _context.Add(station);
                await _context.SaveChangesAsync();
                logger.Info("Station created");
                return RedirectToAction(nameof(Index));
            }
            logger.Info("Station not valid");
            return View(station);
        }

        // GET: Stations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                logger.Error("Id not found");
                return NotFound();
            }

            var station = await _context.Station.FindAsync(id);
            if (station == null)
            {
                return NotFound();
            }
            return View(station);
        }

        // POST: Stations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,LocationX,LocationY,Notes")] Station station)
        {
            if (id != station.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(station);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StationExists(station.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(station);
        }

        // GET: Stations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var station = await _context.Station
                .FirstOrDefaultAsync(m => m.Id == id);
            if (station == null)
            {
                return NotFound();
            }

            return View(station);
        }

        // POST: Stations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var station = await _context.Station.FindAsync(id);
            if (station != null)
            {
                _context.Station.Remove(station);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StationExists(int id)
        {
            return _context.Station.Any(e => e.Id == id);
        }
    }
}

Hovedopgave/Views/Stations/Create.cshtml
@model Hovedopgave.Models.Station

@{
    ViewData["Title"] = "Opret Station";
}

<h1>Opret station</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Stationens navn</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationX" class="control-label">X Lokation</label>
                <input asp-for="LocationX" class="form-control" />
                <span asp-validation-for="LocationX" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationY" class="control-label">Y Lokation</label>
                <input asp-for="LocationY" class="form-control" />
                <span asp-validation-for="LocationY" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label">Noter</label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input style="margin-top: 10px" type="submit" value="Opret" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <button style="margin-top: 10px" accesskey="$0" class="btn btn-secondary" onclick="window.location.href = '/Stations/Index'">Tilbage til liste</button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hovedopgave/Views/Stations/Delete.cshtml
@model Hovedopgave.Models.Station

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Station</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationX)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationX)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationY)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationY)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Slet" class="btn btn-danger" />
        <a class="btn btn-secondary" asp-action="Index">Tilbage til liste</a>
    </form>
</div>

Hovedopgave/Views/Stations/Details.cshtml
@model Hovedopgave.Models.Station

@{
    ViewData["Title"] = "Detaljer";
}

<h1>Stationens detaljer</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationX)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationX)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LocationY)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LocationY)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id">Rediger</a>
    <a class="btn btn-secondary" asp-action="Index">Tilbage til liste</a>
</div>

Hovedopgave/Views/Stations/Edit.cshtml
@model Hovedopgave.Models.Station

@{
    ViewData["Title"] = "Rediger Station";
}

<h1>Rediger Station</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Navn</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationX" class="control-label">X Lokation</label>
                <input asp-for="LocationX" class="form-control" />
                <span asp-validation-for="LocationX" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationY" class="control-label">Y Lokation</label>
                <input asp-for="LocationY" class="form-control" />
                <span asp-validation-for="LocationY" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label">Noter</label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input style="margin-top: 10px" type="submit" value="Gem" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <button style="margin-top: 10px" accesskey="$0" class="btn btn-secondary" onclick="window.location.href = '/Stations/Index'">Tilbage til liste</button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hovedopgave/Views/Stations/Index.cshtml
@model IEnumerable<Hovedopgave.Models.Station>

@{
    ViewData["Title"] = "Stationer";
}

<h1>Stationer</h1>

<p>
    <button class="btn btn-primary" onclick="window.location.href = '/Stations/Create'">Opret ny</button>
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.LocationX)</th>
            <th>@Html.DisplayNameFor(model => model.LocationY)</th>
            <th>@Html.DisplayNameFor(model => model.Notes)</th>
            <th>Muligheder</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="window.location.href='@Url.Action("Details","Stations", new { id = item.Id })'" style="cursor:pointer">
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@item.LocationX.ToString("F2")</td>
                <td>@item.LocationY.ToString("F2")</td>
                <td>@Html.DisplayFor(modelItem => item.Notes)</td>
                <td>
                    <div class="d-flex">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary me-2">Rediger</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-primary">Slet</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>