Hovedopgave/Controllers/TicketsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hovedopgave.Data;
using Hovedopgave.Models;
using Microsoft.AspNetCore.Authorization;
using Hovedopgave.Services;
using System.Diagnostics;
using log4net; 

namespace Hovedopgave.Controllers
{
    [Authorize]
    public class TicketsController : Controller
    {
        private readonly HovedopgaveContext _context;
        private readonly NotificationMailer _mailer;
        private static ILog logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType); 
        public static String? Return { get; set; }

        public TicketsController(HovedopgaveContext context, NotificationMailer mailer)
        {
            _context = context;
            _mailer = mailer;
        }

        //GET: User Tickets
        public async Task<IActionResult> MyTickets()
        {
            Return = "MyTickets";

            int currentUserId = _context.User
                .Where(u => u.Username == User.Identity.Name)
                .Select(u => u.Id)
                .FirstOrDefault();

            return View(await _context.Ticket
                .Include(t => t.Station)
                .Include(t => t.Users)
                .Where(t => t.IsFinished == false)
                .Where(t => t.Users.Any(u => u.Id == currentUserId))
                .OrderByDescending(t => t.Priority)
                .ToListAsync());
        }

        // GET: Open Tickets
        public async Task<IActionResult> Index()
        {
            Return = "Index";

            return View(await _context.Ticket
                .Include(t => t.Station)
                .Where(t => t.IsFinished == false)
                .OrderByDescending(t => t.Priority)
                .ToListAsync());
        }

        // GET: All Tickets
        public async Task<IActionResult> OpenTickets()
        {
            Return = "Index";
            return View(await _context.Ticket.ToListAsync());
        }

        // GET: Closed Tickets
        public async Task<IActionResult> ClosedTickets()
        {
            Return = "ClosedTickets";
            return View(await _context.Ticket
                .Include(t => t.Station)
                .Where(t => t.IsFinished == true)
                .OrderByDescending(t => t.Created)
                .ToListAsync());
        }

        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Users)
                .Include(t => t.Station)
                .Include(t => t.Comments)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            ViewBag.Return = Return;

            return View(ticket);
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(int id, string comment)
        {

            if (string.IsNullOrWhiteSpace(comment))
            {
                ModelState.AddModelError("Comment", "Kommentar kan ikke være tom.");
                return RedirectToAction("Details", new { id });
            }


            var newComment = new Comment
            {
                TicketId = id,
                Created = DateTime.Now,
                CreatedBy = User.Identity.Name,
                Text = comment
            };

            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket == null)
            {
                logger.Warn($"AddComment failed: No ticket found with id={id}"); 
                return NotFound();
            }
            ticket.LastUpdated = DateTime.Now;
            ticket.LastUpdatedBy = User.Identity.Name;
            _context.Update(ticket);

            _context.Comments.Add(newComment);
            await _context.SaveChangesAsync();

            ViewBag.Return = Return;
            return RedirectToAction(nameof(Details), new { id });
        }

        // GET: Tickets/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Ticket ticket, int[] selectedUserIds, int selectedStationId)
        {
            if (ModelState.IsValid)
            {
                if (selectedUserIds != null)
                {
                    foreach (var userId in selectedUserIds)
                    {
                        var user = await _context.User.FindAsync(userId);
                        if (user != null)
                        {
                            ticket.Users.Add(user);
                        }
                    }
                }


                ticket.CreatedBy = User.Identity.Name;
                ticket.LastUpdatedBy = User.Identity.Name;
                _context.Add(ticket);
                await _context.SaveChangesAsync();
                logger.Info($"Ticket {ticket.Id} created by {User.Identity.Name}"); 

                // Notify Users
                await NotifyUsersAboutTicketCreation(ticket);

                return RedirectToAction(Return);
            }

            ViewBag.Users = new SelectList(_context.User, "Id", "FullName");
            ViewBag.Return = Return;
            return View(ticket);
        }

        public IActionResult Create()
        {
            ViewBag.Users = new SelectList(_context.User, "Id", "FullName");
            ViewBag.Stations = new SelectList(_context.Station, "Id", "Name");
            ViewBag.Return = Return;
            return View();
        }

        // GET: Tickets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .Include(t => t.Users)
                .FirstOrDefaultAsync(t => t.Id == id);

            if (ticket == null)
            {
                return NotFound();
            }

            ticket.SelectedUserIds = ticket.Users.Select(u => u.Id).ToArray();
            ViewBag.Users = new SelectList(_context.User, "Id", "FullName");

            ViewBag.Return = Return;


            return View(ticket);
        }

        // POST: Tickets/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Ticket ticket)
        {
            if (id != ticket.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var ticketToUpdate = await _context.Ticket
                        .Include(t => t.Users)
                        .FirstOrDefaultAsync(t => t.Id == ticket.Id);

                    if (ticketToUpdate == null)
                    {
                        logger.Warn($"Edit failed: No ticket found with id={ticket.Id}"); 
                        return NotFound();
                    }

                    ticketToUpdate.Description = ticket.Description;
                    ticketToUpdate.Priority = ticket.Priority;
                    ticketToUpdate.LastUpdated = DateTime.Now;
                    ticketToUpdate.LastUpdatedBy = User.Identity.Name;

                    ticketToUpdate.Users.Clear();
                    if (ticket.SelectedUserIds != null)
                    {
                        foreach (var userId in ticket.SelectedUserIds)
                        {
                            var user = await _context.User.FindAsync(userId);
                            if (user != null)
                            {
                                ticketToUpdate.Users.Add(user);
                            }
                        }
                    }

                    _context.Update(ticketToUpdate);
                    await _context.SaveChangesAsync();
                    logger.Info($"Ticket {ticket.Id} updated by {User.Identity.Name}"); 

                    // Notify users update
                    await NotifyUsersAboutTicketUpdate(ticketToUpdate);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketExists(ticket.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(Return);
            }

            ViewBag.Users = new SelectList(_context.User, "Id", "FullName");
            ViewBag.Return = Return;
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Ticket
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            ViewBag.Return = Return;
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Ticket.FindAsync(id);
            if (ticket != null)
            {
                _context.Ticket.Remove(ticket);
            }

            await _context.SaveChangesAsync();
            logger.Info($"Ticket {id} deleted by {User.Identity.Name}"); 
            return RedirectToAction(Return);
        }

        private bool TicketExists(int id)
        {
            return _context.Ticket.Any(e => e.Id == id);
        }

        public async Task<IActionResult> ChangeStatus(int id)
        {

Hovedopgave/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Hovedopgave.Data;
using Hovedopgave.Models;
using log4net;

namespace Hovedopgave.Controllers
{
    public class UsersController : Controller
    {
        private readonly HovedopgaveContext _context;
        private static ILog logger = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public UsersController(HovedopgaveContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Password,Role,Email,Initials,FullName")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                _context.SaveChanges();

                var newUser = await _context.User
                    .FirstOrDefaultAsync(u => u.Username == user.Username);

                var setting = new NotificationSetting
                {
                    UserId = newUser.Id,
                    EmailNotificationsEnabled = true,
                    Frequency = NotificationFrequency.Always
                };
                _context.NotificationSetting.Add(setting);
                await _context.SaveChangesAsync();
                logger.Info($"User '{user.Username}' created with ID {newUser.Id}");
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Password,Role,Email,Initials,FullName")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                    logger.Info($"User {user.Id} updated");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.User.Any(e => e.Id == user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            if (user != null)
            {
                _context.User.Remove(user);
                await _context.SaveChangesAsync();
                logger.Info($"User {id} deleted");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Hovedopgave/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kommunikations System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hovedopgave.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/wsp.png" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/wsp.png" alt="Logo" style="width: 50px; height: 30px; margin-right: 10px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Hjem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Sager</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="ClosedTickets">Lukkede Sager</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stations" asp-action="Index">Stationer</a>
                        </li>

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Log ind</a>
                            </li>
                        }
                        @if (User.IsInRole("Felt"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="MyTickets">Mine Sager</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Brugere</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Edit">Notifikationer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Log ud</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Hovedopgave
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>